### ISSUE TITLE
Piece images not displayed

### ISSUE THREAD

**Issue by dbyler** [pmorim/obsidian-chess#3]
Hi there, congrats on the new plugin! I just tried installing, but the pieces are coming through as missing images:

![2021-11-18 06-33-42 Obsidian - Obsidian - Textfiles - 2021-11-18 md](https://user-images.githubusercontent.com/57901/142299334-1b5fc2b3-5deb-409f-948d-91abcdab5cad.png)

My setup:
- Obsidian 0.13.2 on macOS
- obsidian-chess 1.1.3 installed via community plugins

**Comment by pmorim** [comment]
Hmm, weird.
Can you show me your `.obsidian/plugins/obsidian-chess` folder?

**Comment by pmorim** [comment]
I never tested on Mac, only Windows, and Linux... the issue might be there.

**Comment by dbyler** [comment]
Hmm, just a main.js and manifest.json file. Maybe the assets didn't come through with the installer?

```
$ ls -al
-rw-r--r--@  1 dbyler  staff  89541 Nov 18 06:30 main.js
-rw-r--r--@  1 dbyler  staff    269 Nov 18 06:30 manifest.json
```

**Comment by dbyler** [comment]
Workaround:

1. Manually download the plugin from your releases page
2. Copy the Assets folder into the live plugin folder
3. Restart Obsidian

**Comment by pmorim** [comment]
Yeah, there seems to be a problem with obsidian copying the assets... I will add that workaround to the README file for now.
I haven't had much free time to continue development in the plugin, you can use other chess plugins like [chesser](https://github.com/SilentVoid13/Chesser) and 
[chessboard](https://github.com/THeK3nger/obsidian-chessboard).

**Comment by liamcain** [comment]
Just a heads up, Obsidian doesn't download any additional assets other than the `main.js` file. So to actually fix the loading, you'll need to rollup the SVG assets into the `main.js` file.
